backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Info"
        file: "data/settings.json"
        fields:
          - { label: "Full Name", name: "name", widget: "string" }
          - { label: "Job Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "text" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "LinkedIn URL", name: "linkedin", widget: "string" }
